import {Dimensions, Platform, StyleSheet} from 'react-native';
import colors from '../../theme/colors';
import scale from '../../scale';
import scaledSize from '../../scaleSize';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: scale(15),
    backgroundColor: '#fff',
  },
  formContainer: {
    width: '100%',
    marginTop: scale(33),
    height: '100%',
  },
  mainLabel: {
    fontFamily: 'SFPro',
    fontSize: 25,
    color: colors.black,
    marginBottom: 14,
    fontWeight: '600',
    lineHeight: 25,
    textAlign: 'center',
  },
  subLabel: {
    fontSize: scaledSize(18),
    padding: 0,
    margin: 0,
    color: colors.black,
    fontFamily: 'SFPro',
    marginBottom: 66,
    fontWeight: 'normal',
    textAlign: 'center',
    lineHeight: 22,
  },
  progressBar: {
    width: '60%',
    height: 8,
    backgroundColor: '#e5e5e5',
    borderRadius: 6,
    overflow: 'hidden',
  },
  progress: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 5,
  },
  stepText: {
    fontSize: 18,
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#2196F3',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
    height: 60,
  },
  backButton: {
    justifyContent: 'center',
    width: '20%',
  },
  skipButton: {
    fontFamily: 'Inter-Regular_',
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'right',
    color: '#000000',
  },
  backButtonText: {
    color: '#2196F3',
    fontSize: 16,
  },
  termsLabel: {
    fontSize: 12,
    width: '100%',
    fontWeight: 'normal',
    fontFamily: 'SFPro',
    color: 'rgba(0, 0, 0, 0.5)',
    marginBottom: scale(72),
    paddingHorizontal: scale(20),
    marginTop: 2,
    lineHeight: 18,
    letterSpacing: 0,
  },
  highlightedTermsLabel: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '500',
    marginBottom: 47,
    textAlign: 'center',
  },
  btnView: {
    ...Platform.select({
      ios: {
        position: 'absolute',
        width: '100%',
        // bottom: Dimensions.get('window').height * 0.15,
        bottom: scale(130),
      },
      android: {
        paddingTop: Dimensions.get('window').height * 0.15,
      },
    }),
  },
  btnContainer: {
    flexDirection: 'row',
    width: '90%',
    borderRadius: 8,
    alignSelf: 'center',
    height: scale(50),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    backgroundColor: '#F0F0F0',
  },
  btnLabel: {
    fontSize: 18,
    color: colors.black,
    fontFamily: 'Inter-Regular',
    padding: 8,
    fontWeight: '500',
  },
  signinLabel: {
    fontSize: 18,
    color: colors.black,
    fontFamily: 'SFPro',
    marginTop: 44,
    marginBottom: 40,
    textAlign: 'center',
  },
  signinLabelRed: {
    fontSize: 18,
    color: colors.pastelRed,
    fontWeight: '700',
  },

  newsLetterContainer: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#f6575f19',
    alignSelf: 'center',
    padding: scale(14),
    borderRadius: 10,
    marginTop: scale(52),
  },
  newsLetterLabel: {
    fontSize: 18,
    fontFamily: 'SFPro',
    color: colors.black,
    margin: 5,
    textAlign: 'left',
    fontWeight: '400',
    width: '75%',
  },
  datePickerContainer: {
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  btnGender: {
    width: '90%',
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: '#E5E5E5',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  genderLabel: {
    color: '#000',
    textAlign: 'center',
    fontSize: 16,
  },
  vSpacer: {
    marginVertical: 7,
  },
  btnImage: {
    flexDirection: 'row',
    width: '90%',
    borderRadius: 8,
    height: 48,
    alignItems: 'center',
    paddingHorizontal: 15,
    margin: 6,
  },
  imageLabel: {
    fontSize: 18,
    color: colors.black,
    paddingHorizontal: 15,
    fontWeight: 'normal',
  },
  // OTP Styling
  otpContainer: {
    marginVertical: 25,
    height: 64,
    alignItems: 'center',
  },
  cell: {
    width: 50,
    height: '100%',
    lineHeight: 60,
    fontSize: 35,
    borderWidth: 1,
    borderColor: '#00000030',
    textAlign: 'center',
    textAlignVertical: 'center',
    justifyContent: 'center',
    fontWeight: '400',
    color: '#000',
    borderRadius: 8,
  },
  focusCell: {
    borderColor: colors.primary,
    color: '#000',
  },
  categoryView: {
    borderBottomWidth: 2,
    paddingVertical: 3,
    borderColor: colors.primary,
    marginHorizontal: 7,
    marginRight: 15,
  },
  categoryLabel: {
    fontFamily: 'SFPro',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: 'rgba(0, 0, 0, 0.5)',
  },
  address: {
    marginTop: 58,
    width: '90%',
    alignSelf: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#F6575F1A',
    padding: 21,
    borderWidth: 0,
    borderRadius: 10,
    gap: 20,
  },
  addressText: {
    fontFamily: 'SFPro',
    fontSize: 18,
    fontWeight: 'normal',
    lineHeight: 22,
    color: colors.black,
    width: '85%',
    alignSelf: 'center',
  },

  header: {
    backgroundColor: 'rgba(249, 249, 249, 0.8)',
    height: 60,
    width: '100%',
    flexDirection: 'row',

    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 0.16,
    paddingHorizontal: 13,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 0,
    shadowOpacity: 1,
  },
  headerIcon: {
    position: 'absolute',
    left: 13,
  },
  headerText: {
    fontSize: 18,
    lineHeight: 22,
    color: colors.black,
    textAlign: 'center',
    alignSelf: 'center',
    fontWeight: '600',
  },
  title: {
    fontFamily: 'SFPro',
    fontSize: 23,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 28,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#000000',
    marginTop: 33,
  },
  subTitle: {
    fontFamily: 'SFPro',
    width: 320,
    alignSelf: 'center',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#000000',
    paddingTop: 14,
    paddingBottom: 30,
  },
  form: {
    width: Dimensions.get('screen').width,
    alignSelf: 'center',
    paddingHorizontal: scale(15),
  },
  country: {
    marginVertical: 40,
  },
});
