import {Dimensions, StyleSheet} from 'react-native';
import colors from '../../theme/colors';
import scale from '../../scale';
import scaledSize from '../../scaleSize';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.white,
  },

  searchContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    width: '100%',
    alignSelf: 'center',
    height: 42,
    borderRadius: 22,
    marginTop: 25,

    alignItems: 'center',
    paddingHorizontal: 15,
  },
  searchInput: {
    fontSize: 18,
    marginLeft: 5,
  },
  categoryLabel: {
    color: 'rgba(0, 0, 0, 0.7)',
    fontFamily: 'SFPro',
    lineHeight: scaledSize(16),
    fontSize: scaledSize(16),
    fontWeight: '500',
    width: '30%',
    textAlign: 'center',
  },
  giftFundContainer: {
    flex: 1,
    width: Dimensions.get('screen').width * 0.9,
    alignSelf: 'center',
    marginTop: 9,
  },
  giftFundBox: {
    flexDirection: 'row',
    width: '100%',
    height: 200,
    alignSelf: 'center',
    borderRadius: 8,
    borderColor: '#d6d6d6',
    borderWidth: 0.2,
    backgroundColor: '#fff',
  },
  indicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    paddingBottom: 20,
  },
  indicator: {
    width: 8,
    height: 8,
    borderRadius: 8 / 2,
    marginHorizontal: 5,
  },
  preferenceLabel: {
    fontSize: 16,
    color: '#000',
    fontWeight: '400',
    textAlignVertical: 'center',
    paddingHorizontal: 6,
  },
  addContainer: {
    alignSelf: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.15)',
    borderBottomColor: '#efeff4',
    width: '100%',
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    flexDirection: 'row',
  },
  addLabel: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '500',
    paddingHorizontal: 6,
    paddingVertical: 15,
    textAlign: 'center',
  },
  userImage: {
    width: 40,
    height: 40,
    position: 'absolute',
    bottom: 10,
    left: 10,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: '#fff',
  },

  giftFundAmountLabel: {
    color: '#000',
    fontSize: 14,
    fontWeight: '500',
    marginTop: 10,
  },
  giftFundDesc: {
    fontSize: 14,
    color: '#000',
    width: '70%',
    fontWeight: 'normal',
    paddingHorizontal: scaledSize(18),
    paddingTop: 8,
  },
  assistantModalContainer: {
    // height: scaledSize(295),
    width: scaledSize(265),
    backgroundColor: '#fff',
    position: 'absolute',
    alignSelf: 'center',
    borderRadius: 10,
    overflow: 'hidden',
  },
  assistantImage: {
    alignSelf: 'center',
    marginTop: scaledSize(34),
    height: 80,
    width: 80,
  },
  assistantMainLabel: {
    color: '#fff',
    fontSize: 29,
    fontFamily: 'SpaceGrotesk-Bold',
    textAlign: 'center',
    marginTop: 27,

    marginBottom: 16,
  },
  assistantSubLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 15,
    width: '80%',
    fontFamily: 'Inter-Regular',
    fontWeight: '500',
    alignSelf: 'center',
    textAlign: 'center',
    marginBottom: 26,
  },
  assistantDivier: {
    width: '100%',
    borderBottomColor: 'rgba(255, 255, 255, 0.5)',
    borderBottomWidth: 0.5,
    marginTop: 8,
  },
  assistantBtnCancelView: {
    height: 44,
    width: '50%',
    justifyContent: 'center',
    borderRightWidth: 0.5,
    borderRightColor: 'rgba(255, 255, 255, 0.5)',
  },
  assistantBtnLabel: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: 17,
    fontFamily: 'SFPro',
    fontWeight: 'normal',
    textAlign: 'center',
    textAlignVertical: 'center',
    borderColor: '#ffffff',
  },
  noProfilesLabel: {
    fontSize: 18,
    width: Dimensions.get('window').width,
    color: '#000',
    fontWeight: '500',
    paddingHorizontal: 12,
    paddingVertical: 40,
    textAlign: 'center',
    alignSelf: 'center',
  },
  profilesContainer: {
    width: 225,
    borderWidth: 1,
    paddingVertical: 15,
    marginEnd: 16,
    borderRadius: 8,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    marginBottom: 18,
    marginTop: 18,
  },
  profileImage: {
    width: 106,
    height: 106,
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 55,
    borderWidth: 1,
    borderColor: '#d6d6d6',
  },
  profileImageBox: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    padding: 8,
    marginVertical: 5,
    alignItems: 'center',
  },
  profileNameLabel: {
    fontFamily: 'SFPro',
    paddingHorizontal: 20,
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 28,
    textAlign: 'center',
    color: '#000000',
    paddingRight: 3,
  },
  profileBirthdayBox: {
    flexDirection: 'row',
    backgroundColor: '#F3F3F3',
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    padding: 8,
    marginVertical: 5,
  },
  profileBirthdayLabel: {
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'SFPro',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000',
    fontWeight: '500',
    paddingHorizontal: 5,
    alignSelf: 'center',
  },
  profileBtnContainer: {
    width: '82%',
    backgroundColor: '#3B3B3B',
    alignSelf: 'center',
    borderRadius: 8,
    marginTop: 15,
  },
  profileBtnLabel: {
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    textAlign: 'center',
    color: '#fff',
    fontWeight: '600',
    lineHeight: 16,
    paddingVertical: 8,
  },
  aboutDivider: {
    width: '100%',
    height: 10,
    // marginVertical: 15,
    backgroundColor: '#EDEDF3',
  },
  aboutContainer: {
    flexDirection: 'row',
    marginHorizontal: 8,
    marginTop: 10,
  },
  aboutImage: {
    width: 40,
    height: 40,
    alignSelf: 'center',
    marginLeft: 15,
    borderRadius: 55,
  },
  aboutLabel: {
    fontSize: 24,
    color: '#000',
    fontFamily: 'SFPro',
    lineHeight: 24,
    fontWeight: '600',
    paddingLeft: scaledSize(16),
    paddingTop: 18,
  },
  aboutQuestion: {
    width: '90%',
    height: 142,
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#f4d8a8',
    marginTop: 8,
    marginBottom: 25,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  aboutQuestionLabel: {
    fontFamily: 'SFPro',
    color: 'rgba(0, 0, 0, 0.7)',
    fontSize: 22,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: 0,
  },
  aboutAnswerContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 15,
  },
  aboutAnswerBox: {
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 21,
    paddingHorizontal: 12,
    backgroundColor: '#EEEDEE',
    marginRight: 5,
  },
  aboutAnswerLabel: {
    fontSize: 16,
    color: '#000',
    fontWeight: '400',
  },
  vGiftContainer: {
    width: Dimensions.get('window').width / 2,
    margin: 8,
    borderWidth: 0.8,
    borderRadius: 10,
    overflow: 'hidden',
    borderColor: '#d6d6d6',
  },
  vGiftImage: {
    width: '100%',
    height: 150,
    alignSelf: 'center',
  },

  vGiftLabel: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
    paddingHorizontal: 15,
    paddingTop: 15,
  },
  vGiftBirthdayLabel: {
    marginBottom: 15,
    fontSize: 14,
    color: '#000',
    fontWeight: '400',
    borderRadius: 13,
    padding: 4,
    marginVertical: 5,
    paddingHorizontal: 15,
  },
  quizContinueLabel: {
    fontSize: 16,
    textAlign: 'center',
    fontWeight: 'normal',
    color: 'rgba(0, 0, 0, 0.5)',
    marginBottom: 2,
    paddingHorizontal: 3,
    paddingVertical: 12,
  },
  wishlistContainer: {
    width: Dimensions.get('window').width / 2,
    margin: 8,
    borderWidth: 0,
    borderRadius: 10,
    overflow: 'hidden',
    borderColor: '#d6d6d6',
  },
  wishlistDesc: {
    fontSize: 14,
    color: '#000',
    width: '80%',
    fontWeight: '400',
    paddingHorizontal: 12,
    paddingVertical: 2,
  },
  wishlistImage: {
    width: '100%',
    height: 150,
    alignSelf: 'center',
    borderRadius: 10,
  },
  wishlistLabel: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
    paddingHorizontal: 15,
    paddingTop: 15,
  },

  preferenceDesc: {
    fontSize: 14,
    color: '#000',
    fontWeight: '400',
    paddingHorizontal: 12,
  },
  preferenceQuestionContainer: {
    width: '90%',
    borderRadius: 20,
    borderWidth: 1,
    alignSelf: 'center',
    borderColor: '#d6d6d6',
    paddingVertical: 10,
    justifyContent: 'center',
    marginTop: 15,
  },
  preferenceQuestion: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  preferenceBtn: {
    flexDirection: 'row',
    borderRadius: 21,
    height: 50,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#d6d6d6',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  preferenceBtnContainer: {
    height: 24,
    width: 24,
    flexDirection: 'row',
    borderRadius: 21,
    alignSelf: 'center',
    margin: 1,
    backgroundColor: '#D3B562',
  },
  preferencesOptionContainer: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    marginTop: 15,
    justifyContent: 'center',
  },
  wishlistCatContainer: {
    width: Dimensions.get('window').width / 2.6,
    margin: 8,
    borderRadius: 10,
    overflow: 'hidden',
  },
  wishlistCatLabel: {
    fontFamily: 'SFPro',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000000',
    paddingVertical: 15,
  },
  categoryCard: {
    // width: Dimensions.get('window').width / 2.5,
    width: scale(135),
    height: scale(83),
    marginRight: 10,
    marginVertical: 20,
    alignSelf: 'center',
    justifyContent: 'flex-end',
  },
  categoryTitle: {
    textAlign: 'center',
    fontFamily: 'SFPro',
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 16,
    letterSpacing: 0,
    position: 'absolute',
    alignSelf: 'center',
    bottom: 8,
  },
  wishlistModalLabel: {
    fontSize: 18,
    color: '#000',
    paddingHorizontal: 10,
  },
  modalBtnTitle: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 27,
    letterSpacing: 0,
    color: '#000000',
    marginTop: 25,
  },
  modalBtnLabel: {
    fontSize: 17,
    fontWeight: 'normal',
    lineHeight: 27,
    letterSpacing: 0,
    color: colors.primary,
    marginTop: 25,
  },
  btnContainer: {
    flexDirection: 'row',
    width: '95%',
    borderRadius: 8,
    alignSelf: 'center',
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: '#D4D3D9',
    marginVertical: 8,
    paddingHorizontal: 5,
  },
  btnLabel: {
    fontSize: 16,
    color: colors.black,
    padding: 6,
    fontWeight: '500',
  },
  inputLabel: {
    fontSize: 22,
    fontWeight: '600',
    color: '#000',
    marginTop: 20,
    marginBottom: 10,
  },
});
