import {Dimensions, StyleSheet} from 'react-native';
import colors from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#EFEFF4',
    alignItems: 'center',
    paddingHorizontal: 16,
  },

  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 20,
  },
  headerIcons: {
    width: 26,
    height: 26,
    textAlign: 'center',
    textAlignVertical: 'center',
    overflow: 'hidden',
  },
  nameLabel: {
    fontFamily: 'SFPro',
    fontSize: 25,
    fontWeight: '600',
    fontStyle: 'normal',
    textAlign: 'center',
    color: '#000000',
    paddingHorizontal: 6,
  },
  birthdayLabel: {
    fontFamily: 'SFPro',
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'normal',
    textAlign: 'center',
    color: '#000000',
    paddingHorizontal: 6,
  },
  countNumber: {
    fontWeight: '600',
  },
  countsLabel: {
    fontFamily: 'SFPro',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 28,
    letterSpacing: 0,
    textAlign: 'center',
    color: 'rgba(0, 0, 0, 0.5)',
    paddingVertical: 10,
  },
  image: {
    width: 118,
    borderRadius: 60,
    aspectRatio: 1,
  },
  categoryCard: {
    width: Dimensions.get('window').width / 5,
    height: 62,
    margin: 5,
    backgroundColor: '#fff',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryLabel: {
    fontFamily: 'SFPro',
    fontSize: 13,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.2,
    textAlign: 'center',
    paddingTop: 8,
    color: 'rgba(0, 0, 0, 0.5)',
  },
  toggleLabel: {
    fontFamily: 'SFPro',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textAlign: 'center',
    color: '#000000',
  },
  giftFundLabel: {
    fontFamily: 'SFPro',
    fontSize: 18,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000000',
  },
  slide: {
    width: '100%',
    borderRadius: 8,
    alignSelf: 'center',
    borderColor: '#000',
    marginVertical: 6,
    height: 195,
    overflow: 'hidden',
  },

  endListContainer: {
    backgroundColor: colors.white,
    height: 72,
    justifyContent: 'center',
    marginBottom: 5,
    padding: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    width: '100%',
  },
  endListSubContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  endListLeftContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  endListLeftSubContainer: {paddingLeft: 10, width: '80%'},
  endListTitleText: {fontWeight: '500', fontSize: 16, color: colors.black},
  endListSubTitleText: {
    fontSize: 15,
    color: colors.fontSubColor,
    fontWeight: '400',
  },
  endListIconContainer: {width: '10%'},
  wishlistLabel: {
    fontFamily: 'SFPro',
    fontSize: 24,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000000',
    marginTop: 10,
    paddingVertical: 5,
  },
  wishlistSubLabel: {
    fontFamily: 'SFPro',
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: 0,
    color: '#3b3b3b',
    paddingVertical: 5,
  },
  questionCard: {
    backgroundColor: '#fff',
    width: '100%',
    alignSelf: 'center',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 12,
    overflow: 'hidden',
    marginTop: 12,
  },
  questionSubCard: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  questionLabel: {
    color: '#000',
    fontWeight: '600',
    fontSize: 16,
    width: '90%',
  },
  listItem: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    marginVertical: 8,
    marginHorizontal: 3,
    borderRadius: 21,
    borderColor: '#E5E5E5',
    borderWidth: 1,
    width: 'auto',
  },
  listLabel: {
    fontSize: 16,
    fontWeight: 'normal',
    color: '#000',
  },
  wishlistModalLabel: {
    fontSize: 18,
    color: '#000',
    paddingHorizontal: 10,
  },
  btnContainer: {
    flexDirection: 'row',
    width: '95%',
    borderRadius: 8,
    alignSelf: 'center',
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: '#D4D3D9',
    marginVertical: 8,
    paddingHorizontal: 5,
  },
  btnLabel: {
    fontSize: 16,
    color: colors.black,
    fontWeight: '500',
  },
  recipientCard: {
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginVertical: 5,
    zIndex: 1,
  },
  bg: {
    width: '95%',
    alignSelf: 'center',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  profile: {
    width: 40,
    height: 40,
    margin: 8,
  },
  textContainer: {
    flex: 1,
    marginVertical: 15,
    marginRight: 'auto',
  },

  arrow: {
    width: 22,
    height: 22,
    position: 'absolute',
    right: 10,
  },
  divider: {
    height: 1,
    width: '100%',
    borderBottomColor: '#d6d6d6',
    borderBottomWidth: 1,
    backgroundColor: '#ff0000',
  },
  headerText: {
    fontSize: 18,
    fontWeight: 'normal',
    color: '#000000',
    overflow: 'hidden',
  },
  multiLineText: {
    color: 'rgba(0, 0, 0, 0.5)',
    width: '95%',
  },
  newLabelText: {
    flexDirection: 'row',
    width: '100%',
    alignSelf: 'center',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginTop: 10,
  },
  inputLabel: {
    fontFamily: 'SFPro',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 24,
    letterSpacing: 0,
    color: '#000000',
    marginTop: 24,
    marginBottom: 10,
  },
  occasionModalContainer: {
    height: '90%',
    width: '100%',
    backgroundColor: '#ECECF3',
    position: 'absolute',
    alignSelf: 'center',
    borderRadius: 12,
    bottom: 0,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingBottom: 25,
  },
  confirmationModalContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 1,
    borderRadius: 15,
    backgroundColor: '#fff',
    paddingHorizontal: 18,
    paddingVertical: 15,
  },
  confirmationLabel: {
    fontFamily: 'SpaceGrotesk',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    textAlign: 'center',
    color: colors.black,
  },
  confirmationSubLabel: {
    fontFamily: 'SpaceGrotesk',
    fontSize: 15,
    padding: 10,
    fontWeight: '300',
    fontStyle: 'normal',
    textAlign: 'center',
    color: colors.black,
  },
  confirmationDivider: {
    borderWidth: 1,
    borderColor: '#E5E5E5',
    width: '100%',
    marginVertical: 5,
  },
  confirmationBtnLabel: {
    fontFamily: 'SpaceGrotesk',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    textAlign: 'center',
    color: colors.primary,
    paddingVertical: 10,
  },
  optionContainer: {
    flexDirection: 'row',
    width: '100%',
    alignSelf: 'center',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 18,
  },
  profileOptions: {
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#000000',
    paddingLeft: 15,
  },
  giftCardHeader: {
    flexDirection: 'row',
    width: '99%',
    justifyContent: 'space-between',
    marginTop: 30,
    paddingVertical: 10,
  },
  giftCardSubContainer: {
    flexDirection: 'row',
    width: '95%',
    height: '95%',
    alignSelf: 'center',
    overflow: 'hidden',
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  giftAmountLabel: {
    color: '#000',
    fontSize: 18,
    fontWeight: '400',
    marginTop: 10,
  },
  giftAmountSubLabel: {
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    paddingVertical: 15,
    color: '#848484',
  },
  giftProfileImage: {
    width: 20,
    height: 20,
    top: 0,
    left: 10,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: '#d6d6d6',
  },
  modalBtnTitle: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 27,
    letterSpacing: 0,
    color: '#000000',
    marginTop: 25,
  },
  modalBtnLabel: {
    fontSize: 17,
    fontWeight: 'normal',
    lineHeight: 27,
    letterSpacing: 0,
    color: colors.primary,
    marginTop: 25,
  },
  wishlistCatContainer: {
    width: Dimensions.get('window').width / 2.6,
    margin: 8,
    borderRadius: 10,
    overflow: 'hidden',
  },
  wishlistCatLabel: {
    fontFamily: 'SFPro',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000000',
    paddingVertical: 10,
  },
  modalContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 35,
  },
  wishlistmodalContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 10,
    height: '100%',
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  shareProfileImage: {
    width: 76,
    borderRadius: 60,
    aspectRatio: 1,
    alignSelf: 'center',
    marginTop: 30,
  },
  shareUsername: {
    fontFamily: 'SpaceGrotesk-Bold',
    fontSize: 30,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 32,
    letterSpacing: -1.2,
    textAlign: 'center',
    color: colors.black,
    marginTop: 14,
    marginBottom: 20,
  },
  shareUserLink: {
    borderColor: 'rgba(0, 0, 0, 0.1)',
    height: 40,
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: 25,
    width: '95%',
    alignSelf: 'center',
    textAlign: 'center',
  },
  shareOptionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
    width: '95%',

    marginBottom: 10,
  },
  userListContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 13,
  },
  userListLeftContainer: {flexDirection: 'row', alignItems: 'center'},
  userListTextStyle: {
    fontFamily: 'SFPro',
    fontSize: 18,
    color: colors.black,
    paddingLeft: 10,
    fontWeight: 'normal',
  },
  userListRightContainer: {paddingEnd: 10},
  profileDivider: {
    width: '120%',
    height: 0.5,
    alignSelf: 'center',
    borderBottomColor: 'rgba(0, 0, 0, 0.15)',
    borderBottomWidth: 1,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  actionList: {
    width: Dimensions.get('screen').width,
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  actionListContainer: {
    backgroundColor: colors.white,
    width: Dimensions.get('screen').width / 3.45,
    marginEnd: 8,
    height: 70,
    paddingHorizontal: 18,
    borderRadius: 10,
    zIndex: 10,
  },
  btnView: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    width: '100%',
    bottom: 0,
  },
  giftButton: {
    alignItems: 'center',
    marginVertical: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 8,
    justifyContent: 'center',
    height: 50,
  },
  giftButtonText: {
    fontFamily: 'Inter-Regular_',
    fontSize: 18,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#ffffff',
  },
  giftFundBox: {
    flexDirection: 'row',
    width: Dimensions.get('screen').width * 0.9,
    height: 200,
    alignSelf: 'center',
    borderRadius: 8,
    backgroundColor: '#fff',
    marginTop: 5,
    marginBottom: 25,
    shadowColor: 'rgba(0, 0, 0, 0.09)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 4,
    shadowOpacity: 1,
    elevation: 5,
  },
  giftFundContainer: {
    flex: 1,
    marginBottom: 10,
    width: Dimensions.get('screen').width * 0.9,
    alignSelf: 'center',
    height: 200,
  },
  cards: {
    flexDirection: 'row',
    width: '90%',
    height: 45,
    alignSelf: 'center',
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 2,
    marginVertical: 5,
    zIndex: 1,
  },
});
