import {Platform, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EDEDF3',
  },
  headerContainer: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#fff',
    height: '8%',
    borderBottomWidth: 0.3,
    borderBottomColor: '#969297',
  },
  headerLView: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRView: {
    width: '20%',
    justifyContent: 'center',
  },
  label: {
    color: '#000',
    fontSize: 18,
    paddingHorizontal: 10,
    fontWeight: '500',
  },

  quizTitle: {
    fontSize: 25,
    textAlign: 'center',
    color: '#000',
    alignSelf: 'center',
    fontWeight: '500',
    paddingVertical: 25,
    paddingHorizontal: 10,
  },

  quizSubTitle: {
    fontSize: 16,
    textAlign: 'center',
    color: '#414041',
    alignSelf: 'center',
    fontWeight: '400',
  },

  bottomBar: {
    height: '10%',
    width: '100%',
    backgroundColor: '#fff',
    borderTopColor: '#969297',
    borderTopWidth: 0.3,
    position: 'absolute',
    alignItems: 'center',
    bottom: 0,
    flexDirection: 'row',
    zIndex: 1,
  },
  bottomBtnContainer: {
    backgroundColor: '#F1F1F2',
    height: 44,
    width: 44,
    margin: '2%',
    borderRadius: 8,
  },
  formContainer: {
    width: '100%',
  },

  listContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    flexGrow: 1,
    width: '95%',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  listItem: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    margin: 5,
    borderRadius: 21,
    borderColor: '#E5E5E5',
    borderWidth: 1,
    width: 'auto',
    // minWidth: 120,
    // maxWidth: '30%',
  },
  listLabel: {
    fontSize: 16,
    color: '#000',
  },

  searchContainer: {
    flexDirection: 'row',
    backgroundColor: '#E3E3E8',
    width: '85%',
    alignSelf: 'center',
    height: 42,
    borderRadius: 22,
    marginVertical: 15,
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  searchInput: {
    fontSize: 18,
    marginLeft: 5,
  },
  modalContainer: {
    backgroundColor: '#EDEDF3',
    height: '90%',
    position: 'absolute',
    bottom: 0,
    width: '100%',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  header: {
    backgroundColor: '#EDEDF3',
    height: '90%',
    position: 'absolute',
    bottom: 0,
    width: '100%',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  headerDragButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 3,
    alignSelf: 'center',
    backgroundColor: '#C4C4CA',
    width: 40,
    height: 5,
    margin: 10,
  },
  headerModalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
  answerLabel: {
    color: '#000',
    fontWeight: '500',
    fontSize: 22,
    width: '80%',
  },
  doneLabel: {
    color: '#ff0000',
    fontWeight: '400',
    fontSize: 18,
  },
  questionCard: {
    backgroundColor: '#fff',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 10,
    padding: 18,
    overflow: 'hidden',
    marginVertical: 5,
  },
  questionSubCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  questionLabel: {
    color: '#000',
    width: '80%',
    fontWeight: '600',
    fontSize: 18,
  },
  quizModalImage: {
    height: 200,
    width: 200,
    alignSelf: 'center',
    marginTop: 30,
  },
  quizModalTitle: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 30,
    textAlign: 'center',
    marginTop: 59,
    width: '80%',
    alignSelf: 'center',
  },
  quizModalLabel: {
    color: '#fff',
    fontWeight: '400',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 30,
    lineHeight: 22,
    alignSelf: 'center',
    width: '85%',
  },
  draggableRow: {
    marginTop: 5,
    width: '90%',
    backgroundColor: '#fff',
    padding: 10,
    alignSelf: 'center',
    borderRadius: 10,
  },
  list: {
    flex: 1,
  },
  contentContainer: {
    width: '100%',
    ...Platform.select({
      ios: {
        paddingHorizontal: 30,
      },
      android: {
        paddingHorizontal: 0,
      },
    }),
  },
});
