import {Platform, StyleSheet} from 'react-native';
import colors from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 5,
    backgroundColor: 'rgba(249, 249, 249, 0.8)',
  },
  title: {
    fontFamily: 'SFPro',
    width: 210,
    height: 40,
    fontSize: 32,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 40,
    letterSpacing: 0,
    color: '#4b494d',
  },
  icon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 22,
    borderColor: '#999999',
    paddingHorizontal: 15,
    paddingVertical: Platform.OS === 'ios' ? 10 : 1,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    marginTop: 20,
    marginBottom: 13,
  },
  searchIcon: {
    width: 18,
    height: 18,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 18,
    color: '#333333',
  },
  mainSection: {
    paddingHorizontal: 16,
    backgroundColor: '#EFEFF4',
  },
  labelContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // height: 55,
    paddingVertical: 17,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.15)',
    paddingHorizontal: 16,
  },
  divider: {
    width: '100%',
    height: 0.5,
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
  },
  selectedLabel: {
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    backgroundColor: '#77777A',
  },
  label: {
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 7,
    fontSize: 14,
    marginEnd: 7,
  },
  selectedLabelText: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  labelText: {
    fontSize: 14,
    color: '#333333',
  },
  imageContainer: {
    marginTop: 24,
    marginBottom: 20,
    backgroundColor: '#efeff4',
  },
  image: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 0.5,
    borderColor: '#d6d6d6',
  },
  imageText: {
    fontFamily: 'SFPro',
    fontWeight: 'normal',
    textAlign: 'center',
    marginVertical: 5,
    color: '#000',
    lineHeight: 18,
    fontSize: 12,
  },
  userView: {
    borderRadius: 10,
    backgroundColor: '#ffffff',
    marginTop: 1,
    paddingVertical: 14,
    paddingHorizontal: 18,
  },
  userDetailsContainer: {
    flexDirection: 'row',
    // margin: 14,
  },
  userName: {
    fontFamily: 'SFPro',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000000',
  },
  userDescription: {
    fontFamily: 'SFPro',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#848484',
  },
  profile: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: '#d6d6d6',
  },
  userDetails: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  userInfo: {
    marginLeft: 14,
    alignSelf: 'center',
  },
  fomateText: {
    marginLeft: 25,
    marginTop: 15,
  },
  notificationIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: -5,
    backgroundColor: '#ffffff',
    borderRadius: 50,
  },
  notificationIcon: {
    width: 22,
    height: 22,
  },
  wishlistModalLabel: {
    fontSize: 18,
    color: '#000',
    paddingHorizontal: 10,
  },
  recipientCard: {
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginVertical: 5,
    zIndex: 1,
  },
  btnContainer: {
    flexDirection: 'row',
    width: '95%',
    borderRadius: 8,
    alignSelf: 'center',
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: '#D4D3D9',
    marginVertical: 8,
    paddingHorizontal: 5,
  },
  btnLabel: {
    fontSize: 16,
    color: colors.black,
    padding: 8,
    fontWeight: '400',
  },
  arrow: {
    width: 22,
    height: 22,
    position: 'absolute',
    right: 10,
  },
  headerText: {
    fontSize: 18,
    fontWeight: 'normal',
    color: '#000000',
    overflow: 'hidden',
  },
  bg: {
    width: '95%',
    alignSelf: 'center',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  textContainer: {
    flex: 1,
    marginVertical: 15,
    marginRight: 'auto',
  },
  multiLineText: {
    color: 'rgba(0, 0, 0, 0.5)',
    width: '95%',
  },
  frequentRecipientContainer: {
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    marginEnd: 13,
  },
  addPictureContainer: {
    width: '60%',
    alignSelf: 'center',
    borderRadius: 12,
    marginBottom: 15,
  },
  imageSelection: {
    height: 150,
    width: 150,
    borderRadius: 75,
    overflow: 'hidden',
    alignSelf: 'center',
    marginVertical: 25,
  },
  modalContainer: {
    height: '90%',
    width: '100%',
    backgroundColor: '#ECECF3',
    position: 'absolute',
    alignSelf: 'center',
    borderRadius: 12,
    bottom: 0,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingBottom: 25,
  },
  modalBtnLabel: {
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 27,
    letterSpacing: 0,
    color: colors.primary,
    marginTop: 25,
  },
  modalNoteLabel: {
    color: '#a3a3a3',
    textAlign: 'left',
    alignSelf: 'center',
    width: '90%',
    marginBottom: 10,
    marginTop: 15,
  },
  modalBirthdayContainer: {
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#fff',
    marginTop: -18,
  },
  outerDivider: {
    height: 1,
    backgroundColor: '#d6d6d6',
    width: '100%',
  },
});
