import {Dimensions, StyleSheet} from 'react-native';
import colors from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.pageBg,
  },
  listItemContainer: {
    paddingHorizontal: 5,
  },
  listItemHeaderText: {
    fontFamily: 'SFPro',
    fontWeight: '500',
    paddingVertical: 21,
    paddingHorizontal: 10,
    color: colors.black,
    fontSize: 18,
  },
  userContainer: {
    alignItems: 'center',
    marginHorizontal: 10,
  },
  profileImage: {
    width: 76,
    height: 76,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#d6d6d6',
  },
  userName: {
    fontSize: 11,
    fontWeight: 'bold',
    marginTop: 10,
    textAlign: 'center',
    color: '#000000',
  },
  subImage: {
    position: 'absolute',
    borderColor: colors.white,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderRadius: 50,
    right: -5,
    bottom: -5,
    width: 25,
    height: 25,
    marginTop: 10,
  },

  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: colors.pageBg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  verticalLine: {
    height: 50,
    position: 'absolute',
    right: -10,
    width: 1,
    backgroundColor: colors.lineColor,
  },
  horizontalLine: {
    borderBottomColor: 'rgba(0, 0, 0, 0.06)',
    borderBottomWidth: 5,
    paddingVertical: 5,
  },
  actionList: {
    width: Dimensions.get('screen').width,
    marginBottom: 23,
    paddingHorizontal: 10,
  },
  actionListContainer: {
    backgroundColor: colors.white,
    width: Dimensions.get('screen').width / 3.5,
    marginRight: 15,
    height: 72,
    paddingHorizontal: 5,
    borderRadius: 10,
    zIndex: 10,
  },
  actionTitleContainer: {padding: 3},
  actionTitleStyle: {
    fontWeight: '600',
    fontSize: 14,
    color: colors.black,
    paddingVertical: 8,
  },
  actionImgContainer: {position: 'absolute', right: -6, bottom: -20},
  actionImgStyle: {
    width: 50,
    height: 50,
  },
  assistantContainer: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  assistantSubContainer: {
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingLeft: 20,

    top: '40%',
  },
  assistantTextStyle: {
    fontSize: 20,
    color: colors.white,
    fontWeight: '500',
    paddingLeft: 10,
  },
  endList: {paddingVertical: 10, paddingHorizontal: 10},
  endListContainer: {
    backgroundColor: colors.white,
    justifyContent: 'center',
    marginBottom: 10,
    padding: 8,
    borderRadius: 10,
    height: 72,
    width: '100%',
  },
  endListSubContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  endListLeftContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '90%',
  },
  endListLeftSubContainer: {paddingLeft: 10, width: '80%'},
  endListTitleText: {fontWeight: '500', fontSize: 16, color: colors.black},
  endListSubTitleText: {
    fontSize: 15,
    color: colors.fontSubColor,
    fontWeight: '400',
  },
  endListIconContainer: {width: '10%'},
  userListContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: colors.gray.medium,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  userListLeftContainer: {flexDirection: 'row', alignItems: 'center'},
  userListTextStyle: {fontSize: 16, color: colors.black, paddingLeft: 10},
  userListRightContainer: {paddingEnd: 10},
  btnView: {
    width: '100%',
    bottom: 0,
  },
  header: {
    paddingHorizontal: 10,
    backgroundColor: colors.white,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  header_left: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  header_text: {
    fontSize: 32,
    color: '#4b494d',
    fontWeight: '600',
    paddingHorizontal: 8,
  },
});
