import {Dimensions, StatusBar, StyleSheet} from 'react-native';
import colors from '../../theme/colors';
import scale from '../../scale';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
    paddingTop: (StatusBar.currentHeight ?? 0) + 40,
  },
  formContainer: {
    width: '100%',
    marginTop: '18%',
    height: '100%',
  },
  mainLabel: {
    fontSize: 25,
    color: colors.black,
    marginBottom: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  subLabel: {
    fontSize: 18,
    color: colors.black,
    marginBottom: 35,
    textAlign: 'center',
    fontWeight: '400',
  },
  progressBar: {
    width: '60%',
    height: 8,
    backgroundColor: '#E5E5E5',
    borderRadius: 5,
    overflow: 'hidden',
    marginLeft: '10%',
  },
  progress: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 5,
  },
  stepText: {
    fontSize: 18,
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#2196F3',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
  },
  backButton: {
    marginRight: 10,
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#2196F3',
    fontSize: 16,
  },
  termsLabel: {
    fontSize: 12,
    color: '#747474',
    marginBottom: 50,
    textAlign: 'center',
  },
  highlightedTermsLabel: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '500',
    marginBottom: 47,
    textAlign: 'center',
  },
  btnView: {
    position: 'absolute',
    width: '100%',
    bottom: Dimensions.get('window').height * 0.15,
  },
  btnContainer: {
    flexDirection: 'row',
    width: '90%',
    borderRadius: 8,
    alignSelf: 'center',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: '#F0F0F0',
  },
  btnLabel: {
    fontSize: 18,
    color: colors.black,
    padding: 8,
    fontWeight: '500',
  },
  signinLabel: {
    fontSize: 18,
    color: colors.black,
    marginTop: 40,
    textAlign: 'center',
    marginBottom: 40,
  },
  signinLabelRed: {
    fontSize: 18,
    color: colors.pastelRed,
    fontWeight: '600',
  },

  newsLetterContainer: {
    width: '90%',
    flexDirection: 'row',
    backgroundColor: '#FEEEEF',
    alignSelf: 'center',
    padding: 20,
    borderRadius: 8,
    marginTop: 51,
  },
  newsLetterLabel: {
    fontSize: 16,
    color: colors.black,
    margin: 5,
    textAlign: 'left',
    fontWeight: '400',
    width: '90%',
  },
  datePickerContainer: {
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  btnGender: {
    width: '90%',
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: '#E5E5E5',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  genderLabel: {
    color: '#000',
    textAlign: 'center',
    fontSize: 16,
  },
  vSpacer: {
    marginVertical: 12,
  },
  btnImage: {
    flexDirection: 'row',
    width: '90%',
    borderRadius: 8,
    height: 48,
    alignItems: 'center',
    paddingHorizontal: 15,
    margin: 6,
  },
  imageLabel: {
    fontSize: 18,
    color: colors.black,
    paddingHorizontal: 10,
    fontWeight: '500',
  },

  // OTP Styling
  otpContainer: {
    marginVertical: 25,
    height: 64,
    alignItems: 'center',
  },
  cell: {
    width: scale(50),
    height: 64,
    lineHeight: 60,
    fontSize: 35,
    borderWidth: 1,
    borderColor: '#00000030',
    textAlign: 'center',
    textAlignVertical: 'center',
    justifyContent: 'center',
    fontWeight: '400',
    color: '#000',
    borderRadius: 8,
  },
  focusCell: {
    borderColor: colors.primary,
    color: '#000',
  },

  categoryView: {
    borderBottomWidth: 2,
    paddingVertical: 3,
    borderColor: colors.primary,
    marginHorizontal: 2,
    marginRight: 15,
    marginBottom: 15,
  },
  categoryLabel: {
    fontFamily: 'SFPro',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: 'rgba(0, 0, 0, 0.5)',
  },
});
