import {Platform, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
  },
  headerContainer: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#fff',
    height: '8%',
    borderBottomWidth: 0.3,
    borderBottomColor: '#969297',
  },
  headerLView: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRView: {
    width: '20%',
    justifyContent: 'center',
  },
  headerRecipient: {
    width: 38,
    height: 38,
    borderRadius: 20,
  },
  label: {
    color: '#000',
    fontSize: 18,
    paddingHorizontal: 10,
    fontWeight: '500',
  },
  subLabel: {
    fontFamily: 'SFPro',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    paddingHorizontal: 10,
    color: 'rgba(0, 0, 0, 0.5)',
  },
  giftLabel: {
    width: '90%',
    fontFamily: 'SFPro',
    fontSize: 25,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 28,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#000000',
    paddingVertical: 25,
  },
  giftSubLabel: {
    fontFamily: 'SFPro',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#3b3b3b',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderColor: '#999999',
    padding: 1,
    paddingHorizontal: 10,
    paddingVertical: Platform.OS === 'ios' ? 10 : 0,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    margin: 10,
  },
  searchIcon: {
    width: 18,
    height: 18,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,

    color: '#333333',
  },
  userDetails: {
    flexDirection: 'row',
    marginLeft: 10,
    alignItems: 'center',
  },
  userInfo: {
    marginLeft: 10,
    alignSelf: 'center',
    width: '70%',
  },
  userDetailsContainer: {
    flexDirection: 'row',
    margin: 10,
  },
  profile: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 0.5,
    borderColor: '#d6d6d6',
  },
  notificationIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: -5,
    backgroundColor: '#ffffff',
    borderRadius: 50,
  },
  notificationIcon: {
    width: 22,
    height: 22,
  },
  userName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
  },
  userDescription: {
    color: 'rgba(0, 0, 0, 0.5)',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    alignItems: 'center',
  },
  divider: {
    width: '100%',
    height: 0.5,
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
  },
  fomateText: {
    marginLeft: 25,
    marginTop: 15,
  },
  userView: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    marginVertical: 4,
    width: '100%',
  },
  bottomBar: {
    height: '10%',
    width: '100%',
    backgroundColor: '#fff',
    borderTopColor: '#969297',
    borderTopWidth: 0.3,
    position: 'absolute',
    alignItems: 'center',
    bottom: 0,
    flexDirection: 'row',
    zIndex: 1,
  },
  bottomBtnContainer: {
    backgroundColor: '#F1F1F2',
    height: 44,
    width: 44,
    justifyContent: 'center',
    alignItems: 'center',
    margin: '2%',
    borderRadius: 8,
  },
  btn: {
    width: '90%',
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: '#E5E5E5',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  btnLabel: {
    fontFamily: 'SFPro',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#000000',
  },
  listItem: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    margin: 5,
    borderRadius: 21,
    borderColor: '#E5E5E5',
    borderWidth: 1,
    width: 'auto',
  },
  listLabel: {
    fontSize: 16,
    color: '#000',
  },
  listContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    flexGrow: 1,
    width: '95%',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  dateLabel: {
    marginBottom: 10,
    fontFamily: 'SFPro',
    fontSize: 18,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000000',
  },
  dateNoteLabel: {
    fontFamily: 'SFPro',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    paddingHorizontal: 15,
    paddingVertical: 10,
    color: 'rgba(0, 0, 0, 0.5)',
  },
  datePickerContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 10,
    borderRadius: 15,
    backgroundColor: '#fff',
    alignItems: 'center',
    paddingHorizontal: 25,
    paddingVertical: 25,
  },
  reminderBox: {
    width: '90%',
    alignSelf: 'center',
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginVertical: 5,
    zIndex: 1,
  },
  reminderLabel: {
    width: '65%',
    fontFamily: 'SpaceGrotesk-Bold',
    fontSize: 27,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 28,
    letterSpacing: -1.25,
    color: '#000000',
    paddingHorizontal: 15,
  },
  reminderNote: {
    fontFamily: 'SFPro',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: '#000000',
    paddingVertical: 8,
  },
  reminderDivider: {
    height: 1,
    backgroundColor: '#d6d6d6',
    width: '100%',
    marginTop: 8,
  },
  budgetLabel: {
    fontFamily: 'SFPro',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    paddingVertical: 1,
    color: 'rgba(0, 0, 0, 0.5)',
  },
  rail: {
    backgroundColor: '#d6d6d6',
    borderRadius: 2,
    flex: 1,
    height: 4,
  },
  railSelected: {
    backgroundColor: '#ff0000',
    borderRadius: 3,
    height: 4,
  },
  priceContainer: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
  },
  priceInputContainer: {
    width: '100%',
    flexDirection: 'row',
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  priceInputBox: {
    borderWidth: 1,
    borderColor: '#d6d6d6',
    width: '45%',
    borderRadius: 10,
    height: 65,
    paddingHorizontal: 10,
  },
  priceLabel: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: 'rgba(0, 0, 0, 0.5)',
    padding: 5,
  },
  currencyLabel: {
    fontSize: 24,
    fontWeight: 'normal',
    fontStyle: 'normal',
    paddingHorizontal: 5,
    paddingRight: 6,
    color: '#363132',
  },
  thumbIcon: {
    width: 24,
    height: 24,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
});
